### ISSUE TITLE
fazer rota que muda status do entregador

### ISSUE THREAD

**Issue by laupontiroli** [laupontiroli/back_ifood_arqproj#11]
fazer uma rota que muda o status de entregador para Disponível

**Comment by jonasbp** [comment]
<img width="875" alt="Captura de Tela 2024-05-06 às 22 40 32" src="https://github.com/laupontiroli/back_ifood_arqproj/assets/5902210/62db69a9-2b54-4720-bd66-c9594c0e3287">

**Comment by jonasbp** [comment]
+ Adição do Swagger
